
import { BlogPost, Category } from './types';

export const SITE_NAME = "PureLife Health";
export const SITE_TAGLINE = "Fitness, Wellness & Active Living";

export const CATEGORIES: Category[] = [
  'Home Workouts', 
  'Weight Loss', 
  'Muscle Building', 
  'Low-Impact', 
  'Senior Fitness', 
  'Recovery', 
  'Nutrition'
];

const AD_HTML = `<div class="ad-placeholder h-48 w-full my-8 bg-gray-50 border border-dashed border-gray-300 flex items-center justify-center text-[10px] font-bold uppercase tracking-widest text-gray-400">In-Article Advertisement</div>`;

export const INITIAL_POSTS: BlogPost[] = [
  // --- HOME WORKOUTS ---
  {
    id: 'hw-1',
    slug: '10-minute-home-workout-busy-professionals',
    title: '10-Minute Home Workout for Busy Professionals: Quick Exercises for Maximum Burn',
    excerpt: 'Short on time but want to stay fit? This 10-minute high-intensity routine is designed for the modern professional.',
    category: 'Home Workouts',
    author: 'Coach Marcus',
    datePublished: '2024-05-20T08:00:00Z',
    dateModified: '2024-05-20T08:00:00Z',
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Professional doing quick workout at home office',
    seoTitle: '10-Minute Home Workout for Busy Professionals | PureLife Health',
    metaDescription: 'Maximize your fitness in just 10 minutes. Perfect home workout for busy professionals with no equipment needed.',
    keywords: ['quick workout', 'busy professional fitness', '10 minute exercise', 'home fitness'],
    content: `<h2>Efficiency Over Duration</h2><p>The biggest barrier to fitness is time. However, science proves that 10 minutes of high-intensity movement can trigger metabolic benefits similar to much longer moderate sessions.</p><h3>The Power Routine</h3><ul><li>Jumping Jacks (1 min)</li><li>Bodyweight Squats (1 min)</li><li>Push-ups (1 min)</li><li>Mountain Climbers (1 min)</li><li>Rest (1 min)</li><li>Repeat Cycle</li></ul>${AD_HTML}<h3>Why Consistency Beats Intensity</h3><p>Doing this daily creates a "habit loop" that makes fitness non-negotiable. For more tips, check our guide on <a href="#/post/create-full-body-home-workout-plan">creating a full-body plan</a>.</p>`
  },
  {
    id: 'hw-2',
    slug: 'create-full-body-home-workout-plan',
    title: 'How to Create a Full-Body Home Workout Plan: Step-by-Step Guide',
    excerpt: 'Stop guessing and start progressing. Learn how to structure a professional-grade workout at home.',
    category: 'Home Workouts',
    author: 'Sarah Jenkins, CPT',
    datePublished: '2024-05-21T09:00:00Z',
    dateModified: '2024-05-21T09:00:00Z',
    image: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Planning a fitness routine on paper',
    seoTitle: 'Create a Full-Body Home Workout Plan | PureLife Health',
    metaDescription: 'Learn how to build a balanced full-body workout plan at home. Step-by-step guidance for beginners.',
    keywords: ['workout plan', 'home gym routine', 'beginner fitness guide', 'full body workout'],
    content: `<h2>The Architecture of a Great Workout</h2><p>A balanced plan ensures all major muscle groups are targeted, preventing imbalances and injuries. You don't need fancy machines; you need a strategy.</p><h3>The Core Components</h3><p>Every session should include a Push, a Pull, a Squat, and a Core movement. This ensures structural integrity. Learn more about <a href="#/post/beginner-muscle-building-no-gym">building muscle without a gym</a>.</p>${AD_HTML}<h3>Scheduling for Success</h3><p>Frequency is key. Aim for 3-4 days a week with rest days in between to allow for muscle repair.</p>`
  },
  {
    id: 'hw-3',
    slug: 'no-equipment-fat-burning-exercises',
    title: 'No-Equipment Fat-Burning Exercises You Can Do Anywhere',
    excerpt: 'Ditch the gym membership. These high-octane bodyweight moves incinerate calories in your living room.',
    category: 'Home Workouts',
    author: 'John Reynolds',
    datePublished: '2024-05-22T10:00:00Z',
    dateModified: '2024-05-22T10:00:00Z',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Man doing burpees in living room',
    seoTitle: 'No-Equipment Fat-Burning Exercises | PureLife Health',
    metaDescription: 'Discover the best bodyweight exercises for fat loss. No equipment needed to burn calories at home.',
    keywords: ['fat burning', 'no equipment', 'bodyweight cardio', 'home fat loss'],
    content: `<h2>Bodyweight: The Ultimate Tool</h2><p>Your body is the only machine you truly need. By moving through large ranges of motion, you demand oxygen and burn fat.</p><h3>Top 3 Movements</h3><ul><li>Burpees: The king of metabolic conditioning.</li><li>High Knees: Explosive cardio in place.</li><li>Plank Jacks: Core and cardio combined.</li></ul>${AD_HTML}<h3>Integrating with Routine</h3><p>Pair these with a <a href="#/post/morning-stretch-routine-energy-boost">morning stretch</a> for a complete wellness start.</p>`
  },
  {
    id: 'hw-4',
    slug: 'morning-stretch-routine-energy-boost',
    title: 'Morning Stretch Routine to Boost Energy at Home: Wake Up in 5 Minutes',
    excerpt: 'Replace your second cup of coffee with this revitalizing mobility sequence.',
    category: 'Home Workouts',
    author: 'Elena Rossi',
    datePublished: '2024-05-23T07:30:00Z',
    dateModified: '2024-05-23T07:30:00Z',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Woman stretching by the window at sunrise',
    seoTitle: 'Morning Stretch Routine for Energy | PureLife Health',
    metaDescription: 'A 5-minute morning stretch routine to increase blood flow and energy levels naturally.',
    keywords: ['morning stretch', 'energy boost', 'mobility routine', 'morning habits'],
    content: `<h2>Wake Up Your Nervous System</h2><p>Static and dynamic stretching in the morning increases circulation and primes your brain for the day ahead.</p><h3>The Sequence</h3><ol><li>Cat-Cow (1 min)</li><li>Child's Pose (1 min)</li><li>Downward Dog (1 min)</li><li>Cobra Stretch (1 min)</li><li>Forward Fold (1 min)</li></ol>${AD_HTML}<h3>Long Term Benefits</h3><p>Regular stretching prevents the common <a href="#/post/home-workout-mistakes-weight-loss">mistakes that hinder weight loss</a>.</p>`
  },
  {
    id: 'hw-5',
    slug: 'home-workout-mistakes-weight-loss',
    title: 'Home Workout Mistakes That Stop You From Losing Weight',
    excerpt: 'Are you working hard but seeing no results? You might be falling into these common fitness traps.',
    category: 'Home Workouts',
    author: 'Dr. Mike Thorne',
    datePublished: '2024-05-24T11:00:00Z',
    dateModified: '2024-05-24T11:00:00Z',
    image: 'https://images.unsplash.com/photo-1591117207239-7ad59a0a79dd?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Frustrated person looking at scale',
    seoTitle: 'Common Home Workout Mistakes | PureLife Health',
    metaDescription: 'Avoid these critical home workout errors that prevent weight loss and muscle gain.',
    keywords: ['weight loss plateaus', 'workout mistakes', 'fitness tips', 'home gym errors'],
    content: `<h2>The "Activity Trap"</h2><p>Many people mistake being "busy" with being "effective." If you aren't seeing results, it's time to audit your form and intensity.</p><h3>Mistake #1: Ignoring Progression</h3><p>Doing the same 20 push-ups every day will only take you so far. Learn about <a href="#/post/progressive-overload-at-home">progressive overload</a> to keep seeing gains.</p>${AD_HTML}<h3>Mistake #2: Poor Nutrition</h3><p>You can't out-train a bad diet. See our <a href="#/post/healthy-eating-exercise-daily-habits">daily habits guide</a>.</p>`
  },

  // --- WEIGHT LOSS ---
  {
    id: 'wl-1',
    slug: 'top-7-fat-burning-exercises',
    title: 'Top 7 Fat-Burning Exercises People Actually Do: Target Stubborn Areas',
    excerpt: 'Belly fat and thigh flab don\'t stand a chance against these high-yield metabolic movements.',
    category: 'Weight Loss',
    author: 'Coach Marcus',
    datePublished: '2024-05-25T08:00:00Z',
    dateModified: '2024-05-25T08:00:00Z',
    image: 'https://images.unsplash.com/photo-1518611012118-2961563f9ec9?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Intense fat burning workout session',
    seoTitle: 'Top 7 Fat-Burning Exercises | PureLife Health',
    metaDescription: 'The 7 most effective exercises for targeted fat loss. Science-backed moves to burn belly fat.',
    keywords: ['fat burn', 'belly fat exercises', 'weight loss moves', 'cardio'],
    content: `<h2>Targeted Fat Loss Myths</h2><p>While you can't "spot reduce" fat, you can increase your overall metabolic rate to burn fat everywhere. These 7 exercises are the most efficient.</p><h3>The Fat-Loss Magnificent 7</h3><ul><li>Sprinting Intervals</li><li>Kettlebell Swings</li><li>Box Jumps</li><li>Thrusters</li><li>Rowing</li><li>Battle Ropes</li><li>Jump Rope</li></ul>${AD_HTML}<h3>Maximize Your Results</h3><p>Combine these with <a href="#/post/combine-cardio-strength-faster-fat-loss">strength training</a> for the ultimate transformation.</p>`
  },
  {
    id: 'wl-2',
    slug: 'combine-cardio-strength-faster-fat-loss',
    title: 'How to Combine Cardio and Strength Training for Faster Fat Loss',
    excerpt: 'Why choose one when you can have both? The hybrid approach to body recomposition.',
    category: 'Weight Loss',
    author: 'Sarah Jenkins, CPT',
    datePublished: '2024-05-26T09:00:00Z',
    dateModified: '2024-05-26T09:00:00Z',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Lifting weights and doing cardio',
    seoTitle: 'Combine Cardio & Strength for Fat Loss | PureLife Health',
    metaDescription: 'The science of concurrent training. How to mix cardio and weights for maximum fat loss.',
    keywords: ['cardio and strength', 'fat loss strategy', 'concurrent training', 'fitness tips'],
    content: `<h2>The Science of Concurrent Training</h2><p>Lifting weights builds metabolically active tissue, while cardio improves heart health and immediate calorie burn.</p><h3>The Strategy</h3><p>Perform strength training first when energy levels are highest, followed by a short burst of cardio. This prevents "interference effect."</p>${AD_HTML}<h3>Nutrition Support</h3><p>Don't forget to fuel. Read about <a href="#/post/protein-workouts-muscle-growth">protein and workouts</a>.</p>`
  },
  {
    id: 'wl-3',
    slug: 'healthy-eating-exercise-daily-habits',
    title: 'Healthy Eating + Exercise: Daily Habits for Natural Weight Loss',
    excerpt: 'Weight loss is a marathon, not a sprint. These daily habits ensure you reach the finish line.',
    category: 'Weight Loss',
    author: 'Nutritionist Elena',
    datePublished: '2024-05-27T10:00:00Z',
    dateModified: '2024-05-27T10:00:00Z',
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Healthy meal prep containers',
    seoTitle: 'Healthy Eating Habits for Weight Loss | PureLife Health',
    metaDescription: 'Sustainable habits for natural weight loss. Combining diet and exercise for long-term health.',
    keywords: ['healthy eating', 'weight loss habits', 'nutrition for fitness', 'daily health'],
    content: `<h2>The 80/20 Rule Revisited</h2><p>You can't out-train a poor diet. Focusing on whole foods, protein, and fiber is the bedrock of success.</p><h3>Habits that Stick</h3><ul><li>Hydrate before every meal.</li><li>Sleep 7-9 hours to manage cortisol.</li><li>Eat protein with every snack.</li></ul>${AD_HTML}<h3>Avoid the Traps</h3><p>Learn more about <a href="#/post/fat-loss-myths-holding-you-back">fat loss myths</a> to stay on track.</p>`
  },
  {
    id: 'wl-4',
    slug: 'fat-loss-myths-holding-you-back',
    title: 'Fat Loss Myths That Are Holding You Back: Debunking Fitness Lies',
    excerpt: 'Is "starvation mode" real? Does lemon water melt fat? We separate fact from fiction.',
    category: 'Weight Loss',
    author: 'Dr. Mike Thorne',
    datePublished: '2024-05-28T11:00:00Z',
    dateModified: '2024-05-28T11:00:00Z',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Question mark made of fitness gear',
    seoTitle: 'Fat Loss Myths Debunked | PureLife Health',
    metaDescription: 'Exposing the most common weight loss lies. Science-based truth about fat burning.',
    keywords: ['fat loss myths', 'weight loss truth', 'fitness lies', 'health facts'],
    content: `<h2>Stop Believing the Hype</h2><p>The fitness industry is full of marketing gimmicks. Real fat loss comes from a consistent caloric deficit and movement.</p><h3>Myth: "Sweating Equals Fat Loss"</h3><p>Sweat is just water loss for temperature regulation. Actual fat burn happens via breath and metabolic waste.</p>${AD_HTML}<h3>Learn the Best Moves</h3><p>Check out our <a href="#/post/best-20-minute-workouts-burn-fat">20-minute fat burn routines</a>.</p>`
  },
  {
    id: 'wl-5',
    slug: 'best-20-minute-workouts-burn-fat',
    title: 'Best 20-Minute Workouts to Burn Fat at Home: Short and Effective',
    excerpt: 'No time? No problem. These 20-minute routines are designed to keep your heart rate high and fat burning.',
    category: 'Weight Loss',
    author: 'Coach Marcus',
    datePublished: '2024-05-29T12:00:00Z',
    dateModified: '2024-05-29T12:00:00Z',
    image: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Person doing intensive cardio',
    seoTitle: '20-Minute Fat Burn Home Workout | PureLife Health',
    metaDescription: 'High-intensity 20-minute workouts for home fat loss. Save time and get shredded.',
    keywords: ['20 minute workout', 'home fat loss', 'HIIT routine', 'quick fitness'],
    content: `<h2>Maximum Intensity, Minimum Time</h2><p>The Tabata method is perfect for these sessions. 20 seconds of work, 10 seconds of rest. Repeat for 8 rounds.</p><h3>Sample Circuit</h3><ul><li>Mountain Climbers</li><li>Squat Jumps</li><li>Alternating Lunges</li><li>Burpees</li></ul>${AD_HTML}<h3>Scale Your Fitness</h3><p>Combine this with <a href="#/post/10-minute-home-workout-busy-professionals">10-minute micro-workouts</a> throughout the day.</p>`
  },

  // --- MUSCLE BUILDING ---
  {
    id: 'mb-1',
    slug: 'beginner-muscle-building-no-gym',
    title: 'Beginner’s Guide to Muscle Building Without a Gym: Bodyweight Strength',
    excerpt: 'Think you need a heavy squat rack to build muscle? Think again. Your own weight is enough.',
    category: 'Muscle Building',
    author: 'John Reynolds',
    datePublished: '2024-05-30T08:00:00Z',
    dateModified: '2024-05-30T08:00:00Z',
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Man doing bodyweight pullups',
    seoTitle: 'Muscle Building Without a Gym Guide | PureLife Health',
    metaDescription: 'Complete guide to building muscle with bodyweight exercises. Effective home strength training.',
    keywords: ['muscle building', 'bodyweight strength', 'home workouts', 'hypertrophy'],
    content: `<h2>The Mechanics of Hypertrophy</h2><p>Muscle growth requires tension, damage, and metabolic stress. You can achieve all three at home by manipulating tempo and volume.</p><h3>The Big Three Home Moves</h3><p>Push-ups, Pull-ups (on a door bar), and Split Squats form the foundation of a muscular physique.</p>${AD_HTML}<h3>Advanced Techniques</h3><p>Learn about <a href="#/post/progressive-overload-at-home">progressive overload</a> to keep growing without heavier weights.</p>`
  },
  {
    id: 'mb-2',
    slug: 'top-5-home-exercises-strong-arms-legs',
    title: 'Top 5 Home Exercises to Build Strong Arms and Legs: Step-by-Step Tips',
    excerpt: 'Focus your efforts on these 5 heavy-hitters to transform your limb strength and aesthetics.',
    category: 'Muscle Building',
    author: 'Sarah Jenkins, CPT',
    datePublished: '2024-05-31T09:00:00Z',
    dateModified: '2024-05-31T09:00:00Z',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Strong arms doing pushups',
    seoTitle: 'Top 5 Home Exercises for Arms and Legs | PureLife Health',
    metaDescription: 'Build strong limbs at home with these 5 essential exercises. Step-by-step instructions included.',
    keywords: ['arm exercises', 'leg exercises', 'home strength', 'muscle growth'],
    content: `<h2>Building the Limbs</h2><p>Arms and legs are often what people want to tone or build first. These 5 moves are non-negotiable for a strong look.</p><h3>The Exercises</h3><ol><li>Diamond Push-ups (Triceps/Chest)</li><li>Bulgarian Split Squats (Quads/Glutes)</li><li>Inverted Rows (Biceps/Back)</li><li>Calf Raises (Lower Leg)</li><li>Pike Push-ups (Shoulders)</li></ol>${AD_HTML}<h3>Support Your Growth</h3><p>Don't forget <a href="#/post/protein-workouts-muscle-growth">protein intake</a> is crucial for repair.</p>`
  },
  {
    id: 'mb-3',
    slug: 'protein-workouts-muscle-growth',
    title: 'Protein & Workouts: How to Fuel Muscle Growth at Home',
    excerpt: 'Lifting is only half the battle. If you aren\'t eating enough protein, your muscles can\'t repair.',
    category: 'Muscle Building',
    author: 'Nutritionist Elena',
    datePublished: '2024-06-01T10:00:00Z',
    dateModified: '2024-06-01T10:00:00Z',
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Protein shake and healthy meal',
    seoTitle: 'Protein for Muscle Growth Guide | PureLife Health',
    metaDescription: 'Everything you need to know about protein timing and intake for home muscle building.',
    keywords: ['protein', 'muscle fuel', 'nutrition for growth', 'post workout meal'],
    content: `<h2>The Building Blocks of Life</h2><p>Amino acids are the building blocks of muscle. Without an adequate supply, your body will actually break down muscle for energy.</p><h3>How Much Do You Need?</h3><p>Aim for 0.8g to 1g of protein per pound of bodyweight for optimal growth. Good sources include eggs, chicken, lentils, and Greek yogurt.</p>${AD_HTML}<h3>Avoid Common Errors</h3><p>Many beginners make <a href="#/post/mistakes-beginners-muscle-gain">these critical muscle-building mistakes</a>.</p>`
  },
  {
    id: 'mb-4',
    slug: 'mistakes-beginners-muscle-gain',
    title: 'Mistakes Beginners Make While Trying to Gain Muscle: Avoid Injury',
    excerpt: 'More is not always better. Learn the common pitfalls that lead to injury and frustration.',
    category: 'Muscle Building',
    author: 'Dr. Mike Thorne',
    datePublished: '2024-06-02T11:00:00Z',
    dateModified: '2024-06-02T11:00:00Z',
    image: 'https://images.unsplash.com/photo-1541534401786-2077ee8bca26?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Person lifting with bad form',
    seoTitle: 'Beginner Muscle Building Mistakes | PureLife Health',
    metaDescription: 'Exposing common errors in home muscle building. Stay safe and see results faster.',
    keywords: ['muscle gain mistakes', 'injury prevention', 'beginner lifting', 'fitness tips'],
    content: `<h2>The "Ego" Problem</h2><p>Focusing on reps over form is the fastest way to the hospital. Quality always trumps quantity in hypertrophy.</p><h3>The Top 3 Mistakes</h3><ul><li>Inadequate Rest: Muscles grow while you sleep, not while you work.</li><li>Poor Range of Motion: "Half reps" get "half results."</li><li>Lack of Variety: Muscles adapt quickly to the same stress.</li></ul>${AD_HTML}<h3>Master the Basics</h3><p>Follow our <a href="#/post/beginner-muscle-building-no-gym">beginner's guide</a> for solid foundations.</p>`
  },
  {
    id: 'mb-5',
    slug: 'progressive-overload-at-home',
    title: 'Progressive Overload at Home: How to Get Stronger Without Weights',
    excerpt: 'The secret sauce of strength. Learn how to constantly challenge your body as you get stronger.',
    category: 'Muscle Building',
    author: 'Coach Marcus',
    datePublished: '2024-06-03T12:00:00Z',
    dateModified: '2024-06-03T12:00:00Z',
    image: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Tracking workout progress in a journal',
    seoTitle: 'Progressive Overload Home Workout | PureLife Health',
    metaDescription: 'How to use progressive overload at home without gym weights. Increase strength naturally.',
    keywords: ['progressive overload', 'home strength', 'fitness science', 'muscle growth'],
    content: `<h2>Keep the Challenge Alive</h2><p>The body only changes when it is forced to adapt to a new stimulus. If you can do 50 pushups easily, you aren't building muscle anymore.</p><h3>Ways to Overload Without Weights</h3><ul><li>Tempo Training: Slow down the eccentric phase.</li><li>Increase Volume: More sets and reps.</li><li>Decrease Rest: Shorten recovery time between sets.</li><li>Mechanical Advantage: Switch to more difficult variations (e.g., Archer Pushups).</li></ul>${AD_HTML}<h3>Build Strong Limbs</h3><p>Apply these rules to our <a href="#/post/top-5-home-exercises-strong-arms-legs">arm and leg routine</a>.</p>`
  },

  // --- LOW IMPACT ---
  {
    id: 'li-1',
    slug: '5-simple-yoga-poses-relieve-stress',
    title: '5 Simple Yoga Poses to Relieve Stress Daily: Quick Routine',
    excerpt: 'Calm your mind and stretch your body with these beginner-friendly yoga poses.',
    category: 'Low-Impact',
    author: 'Elena Rossi',
    datePublished: '2024-06-04T08:00:00Z',
    dateModified: '2024-06-04T08:00:00Z',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Woman doing calm yoga pose',
    seoTitle: 'Simple Yoga Poses for Stress Relief | PureLife Health',
    metaDescription: 'Relieve stress with these 5 easy yoga poses. Perfect for beginners and busy schedules.',
    keywords: ['yoga for stress', 'beginner yoga', 'daily stretching', 'mental wellness'],
    content: `<h2>Mind-Body Connection</h2><p>Yoga isn't just about flexibility; it's about regulating the nervous system. These 5 poses target the vagus nerve to induce calm.</p><h3>The Routine</h3><ul><li>Child's Pose (Balasana)</li><li>Cat-Cow (Chakravakasana)</li><li>Legs Up the Wall (Viparita Karani)</li><li>Tree Pose (Vrksasana)</li><li>Corpse Pose (Savasana)</li></ul>${AD_HTML}<h3>Combine with Core</h3><p>Pair yoga with <a href="#/post/beginner-pilates-home-core-strength">Pilates</a> for a strong, stable body.</p>`
  },
  {
    id: 'li-2',
    slug: 'beginner-pilates-home-core-strength',
    title: 'Beginner Pilates at Home: Improve Core Strength Safely',
    excerpt: 'Build a rock-solid core and improve posture with these fundamental Pilates movements.',
    category: 'Low-Impact',
    author: 'Elena Rossi',
    datePublished: '2024-06-05T09:00:00Z',
    dateModified: '2024-06-05T09:00:00Z',
    image: 'https://images.unsplash.com/photo-1518611012118-2961563f9ec9?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Doing pilates on a mat',
    seoTitle: 'Beginner Pilates Home Workout | PureLife Health',
    metaDescription: 'Strengthen your core at home with Pilates. Beginner guide to safe and effective core training.',
    keywords: ['pilates for beginners', 'core strength', 'home pilates', 'posture correction'],
    content: `<h2>The Powerhouse</h2><p>In Pilates, the "powerhouse" refers to the core muscles. Strengthening them protects the spine and improves athletic performance.</p><h3>The Fundamental Moves</h3><ul><li>The Hundred: Classic core endurance.</li><li>Single Leg Stretch: Focus on stability.</li><li>The Roll Up: Articulating the spine.</li></ul>${AD_HTML}<h3>Joint Health</h3><p>Pilates is excellent <a href="#/post/low-impact-cardio-burns-fat">low-impact cardio</a> that protects your joints.</p>`
  },
  {
    id: 'li-3',
    slug: 'walking-weight-loss-steps-needed',
    title: 'Walking for Weight Loss: How Many Steps Do You Really Need?',
    excerpt: 'Is 10,000 steps a marketing myth? We explore the science of walking for fat loss.',
    category: 'Low-Impact',
    author: 'John Reynolds',
    datePublished: '2024-06-06T10:00:00Z',
    dateModified: '2024-06-06T10:00:00Z',
    image: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Person walking in a park',
    seoTitle: 'Walking for Weight Loss Guide | PureLife Health',
    metaDescription: 'How many steps should you take to lose weight? The science-based truth about walking for fitness.',
    keywords: ['walking for weight loss', 'daily steps', 'low impact cardio', 'fat loss walking'],
    content: `<h2>The Simple Power of Steps</h2><p>Walking is the most underrated form of exercise. It is sustainable, low-impact, and can be done anywhere.</p><h3>The Science of 10,000</h3><p>While 10k is a great goal, research shows significant benefits starting at just 7,000 steps. Focus on intensity—power walking is more effective than a stroll.</p>${AD_HTML}<h3>Daily Flexibility</h3><p>Keep your legs limber with a <a href="#/post/daily-stretching-routine-flexibility">daily stretching routine</a>.</p>`
  },
  {
    id: 'li-4',
    slug: 'low-impact-cardio-burns-fat',
    title: 'Low-Impact Cardio That Burns Fat Without Hurting Your Joints',
    excerpt: 'Save your knees and hips while torching calories. Perfect for seniors and post-injury fitness.',
    category: 'Low-Impact',
    author: 'Dr. Sarah Wellness',
    datePublished: '2024-06-07T11:00:00Z',
    dateModified: '2024-06-07T11:00:00Z',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Swimming for cardio',
    seoTitle: 'Joint-Friendly Low Impact Cardio | PureLife Health',
    metaDescription: 'The best low-impact cardio exercises for fat loss. Protect your joints while getting fit.',
    keywords: ['low impact cardio', 'joint health', 'swimming', 'cycling', 'walking'],
    content: `<h2>Intensity Without Impact</h2><p>You don't need to jump to get your heart rate up. Swimming, cycling, and elliptical training provide high metabolic demands with zero impact.</p><h3>Top 3 Alternatives</h3><ul><li>Swimming: Full body engagement.</li><li>Cycling: Excellent for lower body endurance.</li><li>Rowing: High calorie burn, low impact.</li></ul>${AD_HTML}<h3>Morning Energy</h3><p>Boost your results with a <a href="#/post/morning-stretch-routine-energy-boost">morning stretch</a>.</p>`
  },
  {
    id: 'li-5',
    slug: 'daily-stretching-routine-flexibility',
    title: 'Daily Stretching Routine for Flexibility and Pain Relief',
    excerpt: 'Combat the effects of a sedentary lifestyle with this 10-minute full-body stretch.',
    category: 'Low-Impact',
    author: 'Elena Rossi',
    datePublished: '2024-06-08T12:00:00Z',
    dateModified: '2024-06-08T12:00:00Z',
    image: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Person doing deep hamstring stretch',
    seoTitle: 'Daily Stretching for Pain Relief | PureLife Health',
    metaDescription: 'A 10-minute daily stretching routine to improve flexibility and reduce chronic pain.',
    keywords: ['stretching', 'flexibility', 'pain relief', 'daily mobility'],
    content: `<h2>The Importance of Supple Muscles</h2><p>Tight muscles lead to poor posture and chronic pain. Stretching daily keeps your fascia hydrated and your joints mobile.</p><h3>The Pain Relief Protocol</h3><p>Focus on the hips and lower back, where most tension accumulates during office hours.</p>${AD_HTML}<h3>Better Sleep</h3><p>Stretching before bed can improve sleep quality. Also, see our <a href="#/post/5-simple-yoga-poses-relieve-stress">stress-relief yoga guide</a>.</p>`
  }
];
